services:
  web:
    build: .
    container_name: fastapi_app
    command: >
      sh -c "
        python app/db/create_db.py &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=postgres-service
      - DATABASE_PORT=${DATABASE_PORT}
      - SCHEDULER_SECONDS_INTERVAL=${SCHEDULER_SECONDS_INTERVAL}
      - SLACK_WEBHOOK_URL=http://mock-api:8001
      - SLA_CONFIG_PATH=${SLA_CONFIG_PATH}
    depends_on:
      - postgres-service
      - mock-api
    restart: always

  postgres-service:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  mock-api:
    build:
      context: .
      dockerfile: Dockerfile.slack.mock
    container_name: mock_api
    ports:
      - "8001:8001"

volumes:
  postgres-data:
